steps:
# Initialize Terraform
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    env:
      - '_STATE_GCS_BUCKET_NAME=$_STATE_GCS_BUCKET_NAME'
    script: |
      #!/bin/sh
      terraform init -backend-config="bucket=${_STATE_GCS_BUCKET_NAME}"

# Destroy Terraform configuration
  - id: 'tf destroy'
    name: 'hashicorp/terraform:1.0.0'
    script: |
      #!/bin/sh
      terraform destroy -auto-approve
